# Generated by Django 5.1 on 2024-09-04 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_redzone_emergencycontact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="safetypoint",
            old_name="point_type",
            new_name="feature_type",
        ),
    ]
